# Generated by Django 2.0.9 on 2018-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20181103_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='locomotives',
            field=models.ManyToManyField(blank=True, to='stats.Locomotive'),
        ),
    ]
