# Generated by Django 2.1.2 on 2018-11-03 06:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
                ('rate_per_km', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('value', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Locomotive')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('locomotives', models.ManyToManyField(to='stats.Locomotive')),
            ],
        ),
        migrations.AddField(
            model_name='mileage',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Subsidiary'),
        ),
        migrations.AlterUniqueTogether(
            name='mileage',
            unique_together={('locomotive', 'subsidiary', 'year')},
        ),
    ]
